import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { VitePWA } from "vite-plugin-pwa";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    react(),
    mode === "development" && componentTagger(),
    VitePWA({
      registerType: "autoUpdate",
      injectRegister: "inline",
      workbox: {
        // Pre-cache all JS, CSS, fonts, and icons generated by Vite
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
        // Don't cache Supabase API calls or Spotify embeds
        navigateFallback: "/index.html",
        navigateFallbackDenylist: [
          /^\/api\//,
          /xvgoogyagdbgphympzkg\.supabase\.co/,
          /open\.spotify\.com/,
        ],
        // Use stale-while-revalidate for JS/CSS chunks — fast load, background update
        runtimeCaching: [
          {
            urlPattern: /\.(?:js|css)$/,
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "static-chunks",
              expiration: { maxAgeSeconds: 60 * 60 * 24 * 30 }, // 30 days
            },
          },
          {
            urlPattern: /\.(?:woff2|png|ico|svg)$/,
            handler: "CacheFirst",
            options: {
              cacheName: "assets",
              expiration: { maxAgeSeconds: 60 * 60 * 24 * 90 }, // 90 days
            },
          },
          // Section images from Supabase storage — immutable, cache aggressively
          {
            urlPattern: /supabase\.co\/storage\/v1\/object\/public\/.*\.(?:jpg|jpeg|png|webp)$/i,
            handler: "CacheFirst",
            options: {
              cacheName: "section-images",
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
              },
            },
          },
          // Audio clips from Supabase storage
          {
            urlPattern: /supabase\.co\/storage\/v1\/object\/public\/audio-clips\//,
            handler: "CacheFirst",
            options: {
              cacheName: "audio-clips",
              expiration: {
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
              },
            },
          },
          // Google Fonts CSS and woff2 — browser usually caches these but SW ensures it
          {
            urlPattern: /fonts\.(?:googleapis|gstatic)\.com\//,
            handler: "CacheFirst",
            options: {
              cacheName: "google-fonts",
              expiration: {
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
            },
          },
        ],
      },
      manifest: false, // We manage manifest.json ourselves in /public
    }),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
    dedupe: ["react", "react-dom", "react/jsx-runtime", "@supabase/supabase-js"],
  },
  define: { global: "globalThis" },
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("/src/engine/")) return "lyric-engine";
        },
      },
    },
  },
  optimizeDeps: {
    esbuildOptions: { define: { global: "globalThis" } },
  },
}));
