/**
 * ArtistDNA — The permanent visual identity fingerprint for an artist.
 * Generated by AI from the artist's self-description of their music.
 * Stored on the profile and applied to all future Hook Dance videos.
 */

export interface ArtistDNA {
  fingerprint_id: string;

  typography: {
    font_family: string;
    font_weight: number;
    font_style: "normal" | "italic";
    letter_spacing: number;
    text_transform: "uppercase" | "lowercase" | "none";
    layout_bias: "centered" | "stacked" | "expanded" | "arc";
  };

  palette: {
    primary: string;
    accent: string;
    background_base: string;
    background_atmosphere: string;
    temperature: "cold" | "warm" | "split";
  };

  physics_bias: {
    mass_modifier: number;
    damping_modifier: number;
    heat_modifier: number;
    system_weights: {
      fracture: number;
      pressure: number;
      breath: number;
      combustion: number;
      orbit: number;
    };
  };

  background_world: {
    type: string;
    description: string;
    particle_behavior: "none" | "rising" | "falling" | "drifting" | "orbiting";
    beat_response: string;
  };

  tension_signature: {
    gap_score: number;
    resolution: "resolves" | "never_resolves";
    signature_line: string;
  };
}

/** Song context sent alongside the artist's inputs */
export interface FingerprintSongContext {
  bpm?: number;
  mood?: string;
  physics_system?: string;
  hook_lyric?: string;
  description?: string;
}
