export const CARD_CONTENT_HEIGHT_PX = 320;
const CARD_CHROME_HEIGHT_PX = 60;
export const CARD_TOTAL_HEIGHT_PX = CARD_CONTENT_HEIGHT_PX + CARD_CHROME_HEIGHT_PX;
export const FEED_MAX_WIDTH_PX = 470;
export const FMLY_BAR_HEIGHT_PX = 44;
