/**
 * CinematicDirection — the AI-generated visual direction for a lyric video.
 *
 * Generated by: supabase/functions/cinematic-direction
 * Consumed by: fontResolver, sceneCompiler, LyricDancePlayer, generate-section-images
 */

export interface CinematicDirection {
  /** One-sentence world description */
  description?: string;
  /** Typography plan — font, weight, hero style, per-section behaviors */
  typographyPlan?: {
    system: string;
    primary: string;
    case: string;
    baseWeight: string;
    heroStyle: string;
    accentDensity: string;
    sectionBehavior?: Record<string, string>;
  };
  /** Per-section visual direction */
  sections?: CinematicSection[];

  /** Client-built phrase groupings */
  phrases?: CinematicPhrase[];
  /** Client-detected hook phrase text */
  hookPhrase?: string;

  /** Beat grid summary attached by client */
  beat_grid?: { bpm: number; confidence: number };
}

export interface CinematicSection {
  sectionIndex: number;
  /** One evocative sentence — what the viewer sees */
  description: string;
  /** Visual mood from fixed vocabulary — drives camera, color grading, image style */
  visualMood?: string;
  /** Hex color — drives palette generation */
  dominantColor?: string;
  /** Particle system type */
  texture?: string;
  /** Time boundaries (from audio sections) */
  startSec?: number;
  endSec?: number;
  /** Computed ratios (from enrichSections) */
  startRatio?: number;
  endRatio?: number;
  /** Audio energy level (merged from audio analysis) */
  avgEnergy?: number;
  /** Section role from audio analysis (intro/main/outro) */
  role?: string;
}

export interface CinematicPhrase {
  /** Inclusive range of global word indices: [start, end] */
  wordRange: [number, number];
  /** Most impactful word — UPPERCASE */
  heroWord?: string;
  /** Exit animation for this phrase */
  exitEffect?: 'fade' | 'drift_up' | 'shrink' | 'dissolve' | 'cascade' | 'scatter' | 'slam' | 'glitch' | 'burn';
  /** True if this phrase contains chorus lyrics */
  isChorus?: boolean;
  /** Layout — assigned by client */
  composition?: "stack" | "line" | "center_word";
  bias?: "left" | "center" | "right";
  revealStyle?: "instant" | "stagger_fast" | "stagger_slow";
  holdClass?: "short_hit" | "medium_groove" | "long_emotional";
  presentationMode?: string;
}
