/**
 * CinematicDirection — the AI-generated visual direction for a lyric video.
 *
 * Generated by: supabase/functions/cinematic-direction
 * Consumed by: fontResolver, sceneCompiler, LyricDancePlayer, generate-section-images
 */

export interface CinematicDirection {
  /** One-sentence world description */
  description?: string;
  /** Typography plan — font, weight, hero style, per-section behaviors */
  typographyPlan?: {
    system: string;
    primary: string;
    case: string;
    baseWeight: string;
    heroStyle: string;
    accentDensity: string;
    sectionBehavior?: Record<string, string>;
  };
  /** Per-section visual direction */
  sections?: CinematicSection[];

  /** Client-built phrase groupings */
  phrases?: CinematicPhrase[];
  /** Client-detected hook phrase text */
  hookPhrase?: string;
  /** Client-detected signature/thesis phrase text */
  signaturePhrase?: string;

  /** Beat grid summary attached by client */
  beat_grid?: { bpm: number; confidence: number };
}

export interface CinematicSection {
  sectionIndex: number;
  /** One evocative sentence — what the viewer sees */
  description: string;
  /** Visual mood — drives camera, color grading, image style */
  visualMood?: string;
  /** Hex color — primary emotional color, proposed by model */
  dominantColor?: string;
  /** Particle system type */
  texture?: string;
  /** Time boundaries */
  startSec?: number;
  endSec?: number;
  /** Computed ratios (from enrichSections) */
  startRatio?: number;
  endRatio?: number;
  /** Audio energy level */
  avgEnergy?: number;
  /** Peak energy in section */
  peakEnergy?: number;
  /** Section role (intro/main/outro) */
  role?: string;
  /** AI-suggested hero words for this section */
  heroWords?: string[];
}

export interface CinematicPhrase {
  /** Inclusive range of global word indices: [start, end] */
  wordRange: [number, number];
  /** Most impactful word — UPPERCASE */
  heroWord?: string;
  /** Multiple hero words from section-level AI suggestion */
  heroWords?: string[];
  /** Exit animation for this phrase */
  exitEffect?: 'fade' | 'drift_up' | 'shrink' | 'dissolve' | 'cascade' | 'scatter' | 'slam' | 'glitch' | 'burn';
  /** Layout composition */
  composition?: 'stack' | 'line' | 'center_word';
  /** Horizontal bias */
  bias?: 'left' | 'center' | 'right';
  /** Word reveal timing */
  revealStyle?: 'instant' | 'stagger_fast' | 'stagger_slow';
  /** Hold timing class */
  holdClass?: 'short_hit' | 'medium_groove' | 'long_emotional';
  /** Phrase text */
  text?: string;
  /** Word count */
  wordCount?: number;
  /** Timing */
  start?: number;
  end?: number;
  durationMs?: number;
}
